### ISSUE TITLE
the set of execPath is wrong 

### ISSUE THREAD

**Issue by balboliu** [CrabDude/babel-node-debug#1]
i found that the /usr/local/lib/node_modules/babel-node-debug/node_modules/node-inspector/bin/node-debug.js and line172-line174 is:

if (config.subproc.execPath) {
    options.execPath = config.subproc.execPath
  }

so execPath should be a property of  config.subproc not config

**Comment by CrabDude** [comment]
Resolved in [v1.1.1](https://github.com/CrabDude/babel-node-debug/commit/150387ff23e2b60a61d56401329ef8444bfb7832) by taking a different path using `node-inspector`'s `--nodejs` CLI arguments
