### ISSUE TITLE
babel6 support?

### ISSUE THREAD

**Issue by cmichaelgraham** [CrabDude/babel-node-debug#11]
@CrabDude - i'd like to request modification to support babel6

to use babel6, you just need to change the [package.json babel dependency](https://github.com/CrabDude/babel-node-debug/blob/master/package.json#L19) to

```
    "babel-cli": "^6.4.0",
```

and then change [bode-debug.js](https://github.com/CrabDude/babel-node-debug/blob/master/bin/bode-debug.js#L4) to

``` javascript
var babelNodePath = require.resolve('babel-cli/bin/babel-node')
```

i can do a PR if you like, you can make the change, or i can fork and publish as `babel6-node-debug` - just let me know :smile:

**Comment by albertkawmi** [comment]
@cmichaelgraham thanks for posting this. I made the changes locally in my node_modules folder and the debugger opened up in Chrome with my transpiled source code visible, but it wouldn't run properly (kept crashing). Have you had any problems or are you still using this workaround?

**Comment by CrabDude** [comment]
@cmichaelgraham @albertkawmi Can either / both of you verify if the [PR](https://github.com/CrabDude/babel-node-debug/pull/12/) fixes the issue?

**Comment by albertkawmi** [comment]
@crabdude those were the changes I tried a few days ago but didn't work for me. I will try again tonight.

@cmichaelgraham did it work for you?

**Comment by albertkawmi** [comment]
@CrabDude I tried it again and got it working with that [PR](https://github.com/CrabDude/babel-node-debug/pull/12/). It's not totally reliable/stable but I don't have much experience of using Node Inspector anyway and hadn't used babel-node-debug pre Babel 6 so I can't compare.

For anyone interested in this thread, I'm working around this using [a gulp workflow](https://github.com/albertkawmi/gulp-rollup-babel-nodemon) but it would be nice to get babel-node-inspector working and avoid having to use a build script.

Thanks again. Let me know if I can help further.

**Comment by CrabDude** [comment]
[Happy coding. :smiley: ](https://github.com/crabdude/babel-node-debug/compare/99c6b927d78009ce0a4d65e1e96e79177651fda2...36cbc72f8d6081d32b5890027113dd9bf15bd2ca)
