### ISSUE TITLE
bind all

### ISSUE THREAD

**Issue by kodermax** [CrabDude/babel-node-debug#18]
How can i use for 0.0.0.0
if you have...

```
 setTimeout(function() {
      var debug = new Debugger({
        port: config.subproc.debugPort,
        host: '127.0.0.1'
      })
```

**Comment by CrabDude** [comment]
You can't. See [node-inspector/node-inspector #538](https://github.com/node-inspector/node-inspector/issues/538#issuecomment-71793693).

However, if you use the `node-inspector` executable, it should **just work** with babel and source-maps if I remember correctly. Worst case, just put `debugger;` in the first line of your main entry file.

Closing. Will happily reopen if I'm mistaken on any of the above. =)
