### ISSUE TITLE
SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by sayden** [CrabDude/babel-node-debug#2]
I couldn't manage to make it work.

Using any ES6 syntax file throws me a `SyntaxError: Unexpected reserved word`.

Just using: `babel-node-debug es6File.js`

When using `babel-node es6File.js` I have no errors

Any idea?

**Comment by CrabDude** [comment]
[Fixed](https://github.com/CrabDude/babel-node-debug/commit/150387ff23e2b60a61d56401329ef8444bfb7832). Sorry abou that. The forked node-inspector didn't work under all circumstances.

Try again?

**Comment by sayden** [comment]
Working! Thank you very much!
