### ISSUE TITLE
Need to use a debug port other than 5858

### ISSUE THREAD

**Issue by vasco3** [CrabDude/babel-node-debug#3]

**Comment by CrabDude** [comment]
Care to elaborate? You mean you need it to be configurable via CLI or something? In theory the same arguments as `node-debug` are available.

**Comment by vasco3** [comment]
I'm running my app using `babel-node --ignore '/node_modules/(?!@mymodule)' --debug=2399 index.js`

To replace `--debug=2399`, I was wondering if it this would get overriden since I saw the 5858 as the only port in **bode-debug**
https://github.com/CrabDude/babel-node-debug/blob/master/bin/bode-debug.js#L15-L18

**Comment by CrabDude** [comment]
@vasco3 Oh, good catch. Thanks. The whole project is a big hack, and that code is a hack on a hack, but it should definitely be drawing the port from `node-inspector` config. Will update.

**Comment by CrabDude** [comment]
[Fixed.](https://github.com/CrabDude/babel-node-debug/compare/84556947b1fcda349a53b397220a77f212222ac3...99c6b927d78009ce0a4d65e1e96e79177651fda2) `babel-node-debug`@1.3.0

Use `node-debug` and [`node-inspector`](https://github.com/node-inspector/node-inspector)'s [`--debug-port`](https://github.com/node-inspector/node-inspector#options) flag.

**Comment by vasco3** [comment]
awesome thanks for the soon response
