### ISSUE TITLE
--save-live-edit doesn't work

### ISSUE THREAD

**Issue by arisAlexis** [CrabDude/babel-node-debug#4]
If I start the exact same server.js script with:

bode-debug -p 8081 server.js I get a listening on port 8080 from my app and everything works fine.

If I add the --save-live-edit option then it never starts listening and my app is not active.

**Comment by CrabDude** [comment]
Does the same thing work with `node-inspector`'s `node-debug`?

**Comment by arisAlexis** [comment]
I am closing because if I run node-ispector --save-live-edit and then babel-node --debug it runs ok so it's fine.
