### ISSUE TITLE
babel-node-debug / node-inspector with babel 6.x.x

### ISSUE THREAD

**Issue by aegyed91** [CrabDude/babel-node-debug#7]
Hello there @CrabDude , i thought i give it s shot here too as a last resort. With babel 6 i cannot place a breakpoint to anywhere. :(

I opened an issue about this under node-inspector so you can read it if you want. [#771](https://github.com/node-inspector/node-inspector/issues/771)

Of course i also tried it now with babel-node-debug here is the error i get:

``` sh
/Users/tsm/.nvm/versions/node/v5.0.0/lib/node_modules/babel-node-debug/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126
      if (!option) this.log.error("Unknown option: " + alias + "." + key, ReferenceError);
                           ^

TypeError: Cannot read property 'error' of undefined
    at OptionManager.mergeOptions (/Users/tsm/.nvm/versions/node/v5.0.0/lib/node_modules/babel-node-debug/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:28)
    at OptionManager.addConfig (/Users/tsm/.nvm/versions/node/v5.0.0/lib/node_modules/babel-node-debug/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/Users/tsm/.nvm/versions/node/v5.0.0/lib/node_modules/babel-node-debug/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/Users/tsm/.nvm/versions/node/v5.0.0/lib/node_modules/babel-node-debug/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at compile (/Users/tsm/.nvm/versions/node/v5.0.0/lib/node_modules/babel-node-debug/node_modules/babel-core/lib/api/register/node.js:117:22)
    at normalLoader (/Users/tsm/.nvm/versions/node/v5.0.0/lib/node_modules/babel-node-debug/node_modules/babel-core/lib/api/register/node.js:199:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/tsm/.nvm/versions/node/v5.0.0/lib/node_modules/babel-node-debug/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
```

**Comment by CrabDude** [comment]
Hmmm.... Seems like an odd bug. It's probably a dependency incompatibility issue or maybe I need to lockdown the babel-core version better. Will take a look when I get the chance.

**Comment by aegyed91** [comment]
Allright, thanks in advance

**Comment by chaffeqa** [comment]
getting this on babel6 as well

**Comment by CrabDude** [comment]
@tsm91 @chaffeqa Soooooooooo..... How is that `babel@6` or `babel-core` is getting installed at all since the `package.json` contains the following?

``` js
"dependencies": {
    "babel": "^5.8.23",
    ...
}
```

EDIT: Or maybe it's a problem with incompatible option files as the stack-trace implies. But really though, why is `babel-core` getting installed??

Either way, could y'all please post your options files, or `.babelrc`?

**Comment by aegyed91** [comment]
current (compatible with 5.x.x)

```
{
  "stage": 0
}
```

babel 6.x.x

```
{
  "plugins": [],
  "presets": ["stage-0", "es2015"]
}
```

**Comment by CrabDude** [comment]
@tsm91 Yup. That's it. Thanks.

I'll have to think about this one.... `babel-node-debug` purposefully includes its own `babel` dependency because it kind of violates modularity, so it needs a frozen babel version to work with. Ideally, I don't want to have to republish new versions to track with `babel`, but I'll probably have to until I get them to add API support for what I'm doing.

**Comment by blake-regalia** [comment]
+1

**Comment by subfuzion** [comment]
:+1:

**Comment by JasonStoltz** [comment]
+1

**Comment by gavindoughtie** [comment]
+1

Babel 6 is the latest, and is likely to be with us for a while. I'm sure they'd take a pull from you.

**Comment by poluyanov** [comment]
+1

**Comment by clemmy** [comment]
+1

**Comment by jlobos** [comment]
+1

**Comment by arisAlexis** [comment]
+1

**Comment by balaurzor** [comment]
+1

**Comment by robtarr** [comment]
:+1: 

.babelrc
`{
  "presets": ["es2015"]
}`

**Comment by jonathansamines** [comment]
+1

**Comment by eladkarakuli** [comment]
+1

**Comment by TYRONEMICHAEL** [comment]
+1

**Comment by nightire** [comment]
+1 for this, any news?

**Comment by CrabDude** [comment]
Howdy Everyone. Sorry for the holiday infused delay. I'll be fixing this in the next 24, possibly 48 hours.

**Comment by amcdnl** [comment]
@CrabDude any updates? been fighting this, have a good repo case here: https://github.com/amcdnl/debug-hell

**Comment by trycatchjames** [comment]
+1 @CrabDude thanks in advance.

**Comment by Imater** [comment]
Please, fix it. 48 hours left.

**Comment by swinc** [comment]
Just FYI, it's relatively easy to go back to using plain old node-debug by using the require("babel-register") hook [https://babeljs.io/docs/usage/require/].

The one hiccup for me was babel does not transpile the file that calls require("babel-register") so that file needs to be executable on its own with node (requiring minor refactoring if you were using babel-node-debug to start). All subsequently required files are transpiled though and node-debug works fine.

**Comment by amcdnl** [comment]
as @swinc says that is totally doable, here is a demo project i setup w/ all the different ways to accomplish this: https://github.com/amcdnl/debug-hell .. obvs there is some bugs i was trying to outline for test cases w/ these tools

**Comment by CrabDude** [comment]
Thanks @swinc & @amcdnl for pointing that out. `babel-node-debug` has always been primarily a convenience. Though it may not be desireable, this of course also still works just fine with babel@5.

I didn't have time this week, but I have time next week. Will post updates here.

**Comment by Darmikon** [comment]
6.4.0 - bug still can be reproduced

**Comment by shinux** [comment]
with `5.8.35 (babel-core 5.8.35)`  reproduced.

**Comment by sibelius** [comment]
any progress on this?

**Comment by CodeQueen5M** [comment]
+1

**Comment by CrabDude** [comment]
If I can get a couple of you to verify that the [PR](https://github.com/CrabDude/babel-node-debug/pull/12/) fixes the issue, I'll publish a fix.

**Comment by CrabDude** [comment]
[Happy coding. :smiley: ](https://github.com/crabdude/babel-node-debug/compare/99c6b927d78009ce0a4d65e1e96e79177651fda2...36cbc72f8d6081d32b5890027113dd9bf15bd2ca)
